export const siteConfig = {
  name: "theglobalma - the possibilities are endless",
  title: "theglobalma",
  url: "https://www.theglobalma.org",
  getStartedUrl: "https://www.theglobalma.org",
  ogImage: "/blocks/og-image.png",
  description:
    "TheGlobalMA empowers future innovators through workforce development, technology upskilling, and entrepreneurship training. We connect emerging talent to mentorship, accelerators, and global opportunities to build inclusive, future-ready economies.",
  links: {
    creator: "@theglobalma",
    twitter: "https://x.com/theglobalma",
    instagram: "https://instagram.com/theglobalma",
    linkedin: "https://linkedin.com/company/theglobalma",
    github: "https://github.com/theglobalma",
    email: "mailto:hello@theglobalma.org",
  },
  contact: {
    telephone: "+15873707614",
    email: "hello@theglobalma",
  },
  keywords: [
    "workforce development programs for youth in Calgary",
    "bridging African talent to global innovation markets",
    "technology upskilling for underserved communities",
    "entrepreneurship accelerator for African founders",
    "rural student tech training in Alberta",
    "innovation and entrepreneurship mentorship programs",
    "future-ready skills development for diverse communities",
    "Calgary–Africa innovation collaboration",
    "global entrepreneurship and workforce integration",
    "training local tech talent for global jobs",
    "AI-powered workforce development",
    "digital transformation for small businesses",
    "global tech career pathways",
    "innovation in emerging economies",
    "inclusive entrepreneurship training",
    "Calgary newcomers tech training",
    "newcomers career transition Calgary",
    "Alberta innovation for newcomers",
    "Nigeria entrepreneurship ecosystem",
    "African talent development programs",
    "Africa–Canada innovation bridge",
    "Nigeria career transition support",
    "Africa tech accelerator",
    "inclusive innovation accelerator",
    "tech pathways for immigrants",
    "digital transformation skills training",
    "global innovation for emerging economies",
    "inclusive entrepreneurship for newcomers",
    "Workforce Development for Entrepreneurs",
    "Workforce Development for Businesses",
    "AI-Procurement in Africa",
    "Canada Africa Technology Alliance",
  ],
};

export type SiteConfig = typeof siteConfig;
